name: Workflow
on: [workflow_dispatch, push]
jobs:
  test: # Job ID
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure git for private modules
        env:
          TOKEN: ${{secrets.CI_PAT}}
        run: got config --global url."https://oxygenjunk-test:${TOKEN}@github.com".insteadof "https://github.com"
      - name: Build Go
        uses: ./.github/actions/build-go-services
  create-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create Image
        run: echo "Creating..."