name: Workflow
on: [workflow_dispatch, push]
jobs:
  test: # Job ID
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build Go
        uses: ./.github/actions/build-go-services
      - name: Build docker images
        if: ${{success()}}
        run: echo "Creating..."
  # create-image:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create Image
  #       run: echo "Creating..."