name: Workflow
on: [workflow_dispatch, push]
jobs:
  test: # Job ID
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install GO
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'
      - name: Build app
        run: go build -buildvcs=false
  create-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create Image
        run: echo "Creating..."